version: '3.4'

services:
  webexamplatformbackend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiUrl=http://localhost:60746
    ports:
      - "60746:80"
    depends_on: 
      - db-server
    networks:
      - bothnet 
  db-server:
    environment: 
      - MSSQL_TCP_PORT=1433
      - ACCEPT_EULA=Y
      - SA_PASSWORD=User_123
    ports:
      - "1400:1433"
    networks: 
      - bothnet
    restart: always
  webexamplatfomfrontend:
    ports:
      - "3000:3000"
    stdin_open: true
    networks: 
      - bothnet
    depends_on: 
      - webexamplatformbackend
    command: npm start
networks:
  bothnet:
    driver: bridge
