//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int Id { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string subarea { get; set; }
        public string questions { get; set; }
        public string options { get; set; }
        public string answers { get; set; }
        public string scores { get; set; }
        public Nullable<int> totalScore { get; set; }
        public string type { get; set; }
    }
}
