//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class questionAssign
    {
        public int Id { get; set; }
        public int subAreaId { get; set; }
        public string title { get; set; }
        public string type { get; set; }
        public int score { get; set; }
    }
}
