//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string role { get; set; }
        public string password { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime until { get; set; }
        public byte[] active { get; set; }
        public string full_name { get; set; }
        public System.DateTime birth { get; set; }
        public string contact { get; set; }
    }
}
